import Head from 'next/head';
import Link from 'next/link';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Farkle Scorekeeper</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <h2>Welcome to Farkle ScoreKeeper</h2>
        <Link href={'/add-users'}>
          <a>Add new users here</a>
        </Link>
      </main>
    </div>
  );
}
